name: build_and_deploy

on:
  push:
    branches:
      - master         # Push events on master branch

env:
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: get version
        run: |
          export GITTOOLS="gittools/gitversion:5.1.2-beta1-12-linux-debian-9-netcoreapp3.0"
          echo `docker run --rm -v "$(pwd):/repo" $GITTOOLS /repo | jq -r '.CommitsSinceVersionSource'` > semver.txt

      - name: connect to docker hub
        run: |
          echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login --username tveronezi --password-stdin

      - name: build and push docker image
        run: |
          export SEMVER=`cat semver.txt`
          docker build . -t veronezi/chartmuseum:"$SEMVER"
          docker push veronezi/chartmuseum:"$SEMVER"
